variable "vpc" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}
variable "tags" {}
variable "env" {}
variable "alb" {}
variable "document_db" {}
variable "rds" {}
variable "elastic_cache" {}
variable "rabbitmq" {}
variable "ami" {}
variable "ssh_ingress_cidr" {}
variable "zone_id" {}
variable "app" {}